### ISSUE TITLE
Can't Build chncoind on Linux

### ISSUE THREAD

**Issue by gwdp** [CHNCoin/CHNCoin#5]
**Using:**
- Ubuntu 12.10 x64 Server

**Steps to reproduce:**
- cd CHNCoin/src/
- make -f makefile.unix

**Output:**

```
/bin/sh ../share/genbuild.sh obj/build.h
../share/genbuild.sh: 33: ../share/genbuild.sh: cannot create obj/build.h: Directory nonexistent
../share/genbuild.sh: 34: ../share/genbuild.sh: cannot create obj/build.h: Directory nonexistent
make: *** [obj/build.h] Error 2
```

**Comment by wangchun** [comment]
mkdir obj first

**Comment by gwdp** [comment]
Since it's a process to compile, it shouldn't be user responsibility... 
make file should `mkdir`, ins't it ?

Have compiled many crypto coins and never need to do that..

**Comment by wangchun** [comment]
worldcoin has the same issue.

git does not track empty directory. that is why.

**Comment by gwdp** [comment]
1- This step is not described in `build-unix.txt`..
2- why makefile just don't make the `mkdir` command and create the `obj` directory ??

This is a build process and a build directory. this should NOT be user responsibility... Making obscure steps like that will just make CHNCoin more difficult to be adopted.

**Comment by regtable** [comment]
i know its late but devs can put a readme in there with a ditty.
saves the arse ache i have just had
